name: Build artdaq suite against develop

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_call:

jobs:
  build_against_dev_release:
    name: build_against_dev
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Delete huge unnecessary tools folder
      run: rm -rf /opt/hostedtoolcache

    - uses: cvmfs-contrib/github-action-cvmfs@main

    - name: change dir permission
      run: |
        sudo chmod -R go+rwx /var/lib/cvmfs

    - name: Cache cvmfs cache
      id: cvmfs_cache
      uses: actions/cache@main
      with:
        path: /var/lib/cvmfs/shared
        key: cachecvmfs

    - name: restore dir permission
      run: |
        sudo chown -R cvmfs.cvmfs /var/lib/cvmfs
        sudo chmod -R go-rwx /var/lib/cvmfs

    - name: test cvmfs
      run: |
        ls -l /cvmfs/fermilab.opensciencegrid.org/products/artdaq/spack_areas
    
    - name: Checkout pkg
      uses: actions/checkout@main
      with:
        repository: ${{ github.repository }}
        path: scratch/${{ github.repository }}

    - name: run build in docker container with cvmfs bind mount
      run: |
      
        cd $GITHUB_WORKSPACE/scratch
        cat << EOT > build_pkg.sh
        #!/bin/bash
        
        cd /opt/artdaq
        source /opt/artdaq/setupARTDAQDEMO || exit 1
                
        export REPO=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')
        echo "Copying /scratch/art-daq/\$REPO to srcs \${REPO//_/-}"
        cd srcs
        if [ -d \${REPO//_/-} ];then mv \${REPO//_/-}{,.bak}; fi
        cp -pr /scratch/art-daq/\$REPO \${REPO//_/-}
        cd \${REPO//_/-}
        ref=`git describe --all`
        branch=develop

        if [[ ${ref} =~ "heads/" ]]; then
            branch=${ref//heads\//}
        fi

        echo "Checking out $branch"
        cd  /opt/artdaq/srcs
        for pkg in */;do 
            echo "Updating package \$pkg"
            cd \$pkg
            git stash
            git checkout $branch
            git stash pop
            git pull
            cd ..
        done
        cd /opt/artdaq
                
        # Have to re-add here in case architecture is different
        cd /opt/artdaq
        spack config add config:mpd_user_dir:/opt/artdaq/spack-repos/mpd/

        echo "Starting build"
        spack mpd build 2>&1 | tee -a /scratch/art-daq/build.log
        res=\${PIPESTATUS[0]} # Get result of first command in previous pipe, bash specific
        
        echo "Spack install completed with status code \$res"
        echo "Spack install completed with status code \$res" >>/scratch/art-daq/build.log

        exit \$res
        EOT
        chmod +x build_pkg.sh

        docker run --rm -v /cvmfs:/cvmfs:shared -v $GITHUB_WORKSPACE/scratch:/scratch eflumerf/artdaq-spack:latest /scratch/build_pkg.sh
        
    - name: Check build log for success
      run: |
        grep "Spack install completed with status code 0" ${{ github.workspace }}/scratch/art-daq/build.log

    - name: change dir permission again
      run: |
        sudo chmod -R go+rwx /var/lib/cvmfs
