name: Build Doxygen and publish to GitHub pages

on:
  schedule:
    - cron: "0 5 * * *"
  workflow_dispatch:

jobs:
  build-doxygen:
    name: build_doxygen
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: SUID for tar
      run: sudo chown root /bin/tar && sudo chmod u+s /bin/tar
          
    - name: Fetch artdaq Doxygen docs
      uses: actions/download-artifact@v4
      with:
        name: doxygen
        github-token: ${{ secrets.BOT_CI_ISSUES }}
        repository: art-daq/artdaq

    - name: Fetch otsdaq Doxygen docs
      uses: actions/download-artifact@v4
      with:
        name: doxygen
        github-token: ${{ secrets.BOT_CI_ISSUES }}
        repository: art-daq/otsdaq

    - name: Create index.html
      run: |
        cd docs
        cat << EOT > index.html
        
        <p>artdaq Doxygen landing page</p>

        <a href="artdaq/">artdaq</a><br />
        <a href="artdaq-core/">artdaq-core</a><br />
        <a href="artdaq-core-demo/">artdaq-core-demo</a><br />
        <a href="artdaq-demo/">artdaq-demo</a><br />
        <a href="artdaq-epics-plugin/">artdaq-epics-plugin</a><br />
        <a href="artdaq-mfextensions/">artdaq-mfextensions</a><br />
        <a href="artdaq-utilities/">artdaq-utilities</a><br />
        <a href="otsdaq/">otsdaq</a><br />
        <a href="otsdaq-components/">otsdaq-components</a><br />
        <a href="otsdaq-demo/">otsdaq-demo</a><br />
        <a href="otsdaq-epics/">otsdaq-epics</a><br />
        <a href="otsdaq-prepmodernization/">otsdaq-prepmodernization</a><br />
        <a href="otsdaq-utilities/">otsdaq-utilities</a><br />

        EOT

    - name: Upload artifacts
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./docs/

  deploy_to_github_pages:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs: build-doxygen
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Configure GitHub Pages
        uses: actions/configure-pages@v5
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

