name: "Check whitespace using Git"

permissions:
  contents: read

on:
  workflow_call:
    inputs:
        against-ref:
            required: false
            type: string
        exclude-directories:
            required: false
            type: string


jobs:

  check_git_whitespace:
    name: "Check Git whitespace"
    runs-on: ubuntu-latest

    steps:
    - name: Checkout pkg
      uses: actions/checkout@main
      with:
        repository: ${{ github.repository }}
        path: scratch/${{ github.repository }}
        fetch-depth: 0

    - name: Check for whitespace errors using Git
      run: |
        cd scratch/${{ github.repository }}

        cat << EOT > check_whitespace.sh
        #!/bin/bash

        excluded_dirs="${{ inputs.exclude-directories }}"
        exclude_regex="^(nothingtoseehere"

        for dir in \$excluded_dirs;do
          if [ -d \$dir ] || [ -f \$dir ]; then
            exclude_regex="\${exclude_regex}|\$dir"
          fi
        done
        if [ -f .git_whitespace_exclude ];then
          while read entry;do
            if [ "x\$entry" == "x" ]; then continue; fi
            if [ -d \$entry ] || [ -f \$entry ]; then
              exclude_regex="\${exclude_regex}|\$entry"
            fi
          done < .git_whitespace_exclude
        fi
        exclude_regex="\${exclude_regex})"
        echo "Excluding files from checks via \${exclude_regex}"

        against=${{ inputs.against-ref }}
        if [ "x\$against" == "x" ] || [ "x\$against" == "x0" ]; then
            against=\$(git hash-object -t tree /dev/null)
        fi
        echo "Checking for whitespace differences introduced since commit \$against"

        # Cross platform projects tend to avoid non-ASCII filenames; prevent
        # them from being added to the repository. We exploit the fact that the
        # printable range starts at the space character and ends with tilde.
        badchar=\$(git diff --cached --name-only --diff-filter=A  \$against | grep -vE "\${exclude_regex}" | \
        LC_ALL=C tr -d 'A-Za-z0-9/\n_ .@+-' | wc -c)
        if [ \$badchar != 0 ]
        then
            echo "Check failed: cannot add a file name with non-ASCII or blank char."
            exit 1
        fi


        names=\$( git diff --cached --name-only --diff-filter=AM  \$against | grep -vE "\${exclude_regex}" )

        if [ \${PIPESTATUS[0]} -ne 0 ]; then
            echo "Error running git diff command"
            echo "Error running git diff command" >>/scratch/art-daq/build.log
            exit 1
        fi

        rc=0
        IFS_SAVE=\$IFS
        IFS=\$'\\n'
        for name in \$names
        do
            #echo "Checking whitespace for \$name"
            bname=\$( basename \$name )
            ext=\$(echo \$bname | awk -F. '{if(NF==1) print ""; else print \$NF};' )
            if [[ "\$ext" == "hh" || "\$ext" == "cc" || "\$ext" == "fcl" \
               || "\$ext" == "C" ||  "\$ext" == "h" || "\$ext" == "icc"  || "\$ext" == "cpp" \
               || "\$ext" == "mac" || "\$ext" == "sh" || "\$ext" == "py" || "\$ext" == "pl" \
               || "\$name" =~ "CMakeLists.txt" || "\$ext" == "yml" || "\$ext" == "yaml" \
               || "\$ext" == "html" || "\$ext" == "htm" || "\$ext" == "js" || "\$ext" == "css" \
               ]]; then

                # check whitespace and return non-zero if not allowed

                git diff-index --check --cached \$against "\$name"
                [ \$? -ne 0 ] && rc=1

                if [[ -e "\$name" && \$(tail -c1 "\$name" | wc -l) -eq 0 ]]; then
                    echo "Commit check failed: \$name does not have a terminal newline"
                    rc=1
                fi
            fi
        done
        IFS=\$IFS_SAVE

        if [ \$rc -ne 0 ] ; then
            echo "Github CI detected format errors!"
        fi
        exit \$rc
        EOT
        chmod +x check_whitespace.sh
        ./check_whitespace.sh
