name: Run Clang-Tidy Workflow (otsdaq version)

permissions:
  contents: read

on:
  workflow_call:
    inputs:
        against-ref:
            required: false
            type: string

jobs:

 tidy_single_pkg:
    name: tidy single pkg
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Delete huge unnecessary tools folder
      if: runner.os == 'Linux'
      run: |
        # Space usage before cleanup
        df -h /

        # Remove unused tool caches (comment any required ones with #)
        sudo rm -rf /usr/lib/jvm
        sudo rm -rf /usr/local/.ghcup
        sudo rm -rf /usr/local/lib/android
        sudo rm -rf /usr/local/share/powershell
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /usr/share/swift
        sudo rm -rf "$AGENT_TOOLSDIRECTORY"

        # Verify gains
        df -h /

    - name: SUID for tar
      run: sudo chown root /bin/tar && sudo chmod u+s /bin/tar

    - uses: cvmfs-contrib/github-action-cvmfs@main

    - name: test cvmfs
      run: |
        ls -l /cvmfs/fermilab.opensciencegrid.org/products/artdaq/spack_areas

    - name: Checkout pkg
      uses: actions/checkout@main
      with:
        repository: ${{ github.repository }}
        path: scratch/${{ github.repository }}
        fetch-depth: 0

    - name: Fetch package version
      id: version
      run: |
        cd $GITHUB_WORKSPACE/scratch/${{ github.repository }}
        tag=`git describe --tags --abbrev=0`
        echo "Using tag $tag"
        echo "tag=${tag}" >>$GITHUB_OUTPUT

    - name: change dir permission
      run: |
        sudo mkdir -p /var/lib/cvmfs
        sudo chmod -R 777 /var/lib/cvmfs

    - name: Cache cvmfs cache
      id: cvmfs_cache
      uses: actions/cache@main
      with:
        path: /var/lib/cvmfs/shared
        key: cachecvmfs-${{ steps.version.outputs.tag }}

    - name: restore dir permission
      run: |
        sudo chown -R cvmfs:cvmfs /var/lib/cvmfs
        sudo chmod -R 700 /var/lib/cvmfs

    - name: Pull current Docker image
      run: docker image pull ghcr.io/art-daq/otsdaq-spack:latest

    - name: run clang-tidy in docker container with cvmfs bind mount
      run: |

        cd $GITHUB_WORKSPACE/scratch

        against=${{ inputs.against-ref }}
        if [ "x$against" == "x" ] || [ "x$against" == "x0" ]; then
            against=$(git hash-object -t tree /dev/null)
        fi
        echo "Collecting changed files since commit $against, in git repository ${{ github.repository }}"
        cd ${{ github.repository }}
        names=$( git diff --cached --name-only --diff-filter=AM  $against )

        if [ "x$names" == "x" ]; then
            echo "No changed files"
            echo "No changed files" >$GITHUB_WORKSPACE/scratch/art-daq/build.log
            exit 0
        fi
        echo "Changed files to tidy: $names"

        cd $GITHUB_WORKSPACE/scratch

        cat << EOT > build_pkg.sh
        #!/bin/bash

        cd /opt/otsdaq
        source /opt/otsdaq/setup_ots_rte.sh || exit 1

        export REPO=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')
        names="$names"

        mkdir /scratch/art-daq/build_\$REPO
        cd /scratch/art-daq/build_\$REPO

        spack load --first llvm
        spack compiler find

        export compiler=\$(spack compiler info clang|grep cxx|grep llvm|awk '{print \$3}'|tail -1)
        echo "Compiler is \$compiler"
        cp /opt/otsdaq/srcs/CMakePresets.json /scratch/${{ github.repository }}
        echo "Configuring with cmake --preset default /scratch/${{ github.repository }} -DCMAKE_CXX_COMPILER=\$compiler -DCMAKE_EXPORT_COMPILE_COMMANDS=ON"
        cmake --preset default /scratch/${{ github.repository }} -DCMAKE_CXX_COMPILER=\$compiler -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -Wno-dev

        echo "Running clang-tidy on changed files"
        run-clang-tidy -quiet -warnings-as-errors * \$names  2>&1 | tee -a /scratch/art-daq/build.log
        res=\${PIPESTATUS[0]} # Get result of first command in previous pipe, bash specific

        echo "Clang-tidy completed with status code \$res"
        echo "Clang-tidy completed with status code \$res" >>/scratch/art-daq/build.log

        exit \$res
        EOT
        chmod +x build_pkg.sh
        cat build_pkg.sh

        docker run --rm -v /cvmfs:/cvmfs:shared -v $GITHUB_WORKSPACE/scratch:/scratch ghcr.io/art-daq/otsdaq-spack:latest /scratch/build_pkg.sh
        grep "Clang-tidy completed with status code 0" ${{ github.workspace }}/scratch/art-daq/build.log ||
        grep "No changed files" ${{ github.workspace }}/scratch/art-daq/build.log

    - name: upload build log file
      if: always()
      uses: actions/upload-artifact@main
      with:
        name: build_log
        path: ${{ github.workspace }}/scratch/art-daq/build.log

    - name: change dir permission again
      run: |
        sudo chmod -R 777 /var/lib/cvmfs
