name: Create otsdaq LCOV coverage report

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  schedule:
    - cron: "0 1 * * 4"

  workflow_dispatch:

jobs:
  build_against_dev_release:
    name: build_against_dev
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Delete huge unnecessary tools folder
      run: rm -rf /opt/hostedtoolcache

    - name: SUID for tar
      run: sudo chown root /bin/tar && sudo chmod u+s /bin/tar

    - uses: cvmfs-contrib/github-action-cvmfs@main

    - name: test cvmfs
      run: |
        ls -l /cvmfs/fermilab.opensciencegrid.org/products/artdaq/spack_areas
    
    - name: Checkout pkg
      uses: actions/checkout@main
      with:
        repository: ${{ github.repository }}
        path: scratch/${{ github.repository }}
        fetch-depth: 0

    - name: Fetch package version
      id: version
      run: |
        cd $GITHUB_WORKSPACE/scratch/${{ github.repository }}
        tag=`git describe --tags --abbrev=0`
        echo "Using tag $tag"
        echo "tag=${tag}" >>$GITHUB_OUTPUT

    - name: change dir permission
      run: |
        sudo mkdir -p /var/lib/cvmfs
        sudo chmod -R 777 /var/lib/cvmfs

    - name: Cache cvmfs cache
      id: cvmfs_cache
      uses: actions/cache@main
      with:
        path: /var/lib/cvmfs/shared
        key: cachecvmfs-${{ steps.version.outputs.tag }}

    - name: restore dir permission
      run: |
        sudo chown -R cvmfs:cvmfs /var/lib/cvmfs
        sudo chmod -R 700 /var/lib/cvmfs

    - name: Pull current Docker image
      run: docker image pull ghcr.io/art-daq/otsdaq-spack:latest

    - name: run build in docker container with cvmfs bind mount
      run: |
      
        cd $GITHUB_WORKSPACE/scratch
        cat << EOT > build_pkg.sh
        #!/bin/bash
        
        cd /opt/otsdaq
        source /opt/otsdaq/setup_ots.sh || exit 1
        
        rm -rf spack-repos/scd_recipes/packages/perl-ipc-run3
        spack install --add lcov

        export REPO=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')
        export pkgname=\${REPO//_/-}
        echo "Copying /scratch/art-daq/\$REPO to srcs \$pkgname"
        cd srcs
        if [ -d \$pkgname ];then mv \$pkgname{,.bak}; fi
        cp -pr /scratch/art-daq/\$REPO \$pkgname
        cd \$pkgname
        git config --global --add safe.directory \$PWD
        export ref=\$(git describe --all)
        echo "Described current ref as \${ref}"
        branch=develop

        if [[ "x\${ref}" =~ "xheads/" ]]; then
            echo "Setting branch to \${ref//heads\//}"
            branch=\${ref//heads\//}
        fi

        echo "Checking out \$branch"
        cd  /opt/otsdaq/srcs
        for pkg in */;do 
            echo "Updating package \$pkg"
            cd \$pkg
            git stash
            git checkout \$branch
            git stash pop
            git pull
            cd ..
        done
                
        export OTS_DOXY="DOIT"
        # Have to re-add here in case architecture is different
        cd /opt/otsdaq
        spack config add config:mpd_user_dir:/opt/otsdaq/spack-repos/mpd/
        export CETPKG_J=\$((`cat /proc/cpuinfo|grep processor|tail -1|awk '{print $3}'` + 1))
        export USE_GCOV=1
        
        echo "Starting build"
        spack mpd build -G Ninja -j\$CETPKG_J 2>&1 | tee -a /scratch/art-daq/build.log
        res=\${PIPESTATUS[0]} # Get result of first command in previous pipe, bash specific
        
        echo "Spack install completed with status code \$res"
        echo "Spack install completed with status code \$res" >>/scratch/art-daq/build.log
        
        echo "Collecting coverage data"
        lcov -d . --zerocounters
        lcov -c -i -d . -o otsdaq.base

        spack mpd test
        
        lcov -d . --capture --output-file otsdaq.info
        lcov -a otsdaq.base -a otsdaq.info --output-file otsdaq.total
        lcov --remove otsdaq.total '/cvmfs/*' 'boost/*' '*/products/*' "*/build_${CET_SUBDIR}/*" '/usr/include/curl/*' --output-file otsdaq.info.cleaned
        genhtml -o coverage otsdaq.info.cleaned

        mv coverage /scratch/art-daq
        
        exit \$res
        EOT
        chmod +x build_pkg.sh

        docker run --rm -v /cvmfs:/cvmfs:shared -v $GITHUB_WORKSPACE/scratch:/scratch ghcr.io/art-daq/otsdaq-spack:latest /scratch/build_pkg.sh
        
    - name: Check build log for success
      run: |
        grep "Spack install completed with status code 0" ${{ github.workspace }}/scratch/art-daq/build.log

    - name: upload build log file
      uses: actions/upload-artifact@main
      with:
        name: build_log
        path: ${{ github.workspace }}/scratch/art-daq/build.log

    - name: upload coverage
      uses: actions/upload-artifact@main
      with:
        if-no-files-found: error
        name: doxygen
        path: ${{ github.workspace }}/scratch/art-daq/coverage

    - name: change dir permission again
      run: |
        sudo chmod -R 777 /var/lib/cvmfs
