name: Test Single Pkg Workflow (otsdaq version)

on:
  workflow_call:

jobs:

  build_single_pkg:
    name: build single pkg
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Delete huge unnecessary tools folder
      run: rm -rf /opt/hostedtoolcache

    - uses: cvmfs-contrib/github-action-cvmfs@main

    - name: test cvmfs
      run: |
        ls -l /cvmfs/fermilab.opensciencegrid.org/products/artdaq/spack_areas
    
    - name: Checkout pkg
      uses: actions/checkout@main
      with:
        repository: ${{ github.repository }}
        path: scratch/${{ github.repository }}
        fetch-depth: 0

    - name: Fetch package version
      id: version
      run: |
        cd $GITHUB_WORKSPACE/scratch/${{ github.repository }}
        tag=`git describe --tags --abbrev=0`
        echo "Using tag $tag"
        echo "tag=${tag}" >>$GITHUB_OUTPUT

    - name: change dir permission
      run: |
        sudo chmod -R go+rwx /var/lib/cvmfs

    - name: Cache cvmfs cache
      id: cvmfs_cache
      uses: actions/cache@main
      with:
        path: /var/lib/cvmfs/shared
        key: cachecvmfs-${{ steps.version.outputs.tag }}

    - name: restore dir permission
      run: |
        sudo chown -R cvmfs.cvmfs /var/lib/cvmfs
        sudo chmod -R go-rwx /var/lib/cvmfs

    - name: Pull current Docker image
      run: docker image pull ghcr.io/art-daq/otsdaq-spack:latest

    - name: run build in docker container with cvmfs bind mount
      run: |
      
        cd $GITHUB_WORKSPACE/scratch
        cat << EOT > build_pkg.sh
        #!/bin/bash
        
        cd /opt/otsdaq
        source /opt/otsdaq/setup_ots.sh || exit 1
        
        export REPO=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')
        mkdir /scratch/art-daq/build_\$REPO
        cd /scratch/art-daq/build_\$REPO
        
        export CETPKG_J=\$((`cat /proc/cpuinfo|grep processor|tail -1|awk '{print $3}'` + 1))
        export compiler=\$(spack compiler info gcc@13.1.0|grep cxx|awk '{print \$3}')
        echo "Compiler is \$compiler"
        cp /opt/otsdaq/srcs/CMakePresets.json /scratch/art-daq/\$REPO
        echo "Configuring with cmake --preset default /scratch/art-daq/\$REPO -DCMAKE_CXX_COMPILER=\$compiler -Wno-dev"
        cmake --preset default /scratch/art-daq/\$REPO -DCMAKE_CXX_COMPILER=\$compiler -Wno-dev

        echo "Compiling code"
        make -j\$CETPKG_J 2>&1 | tee -a /scratch/art-daq/build.log
        res=\${PIPESTATUS[0]} # Get result of first command in previous pipe, bash specific
        
        if [ \$res -eq 0 ]; then
            echo "Starting tests"
            make test 2>&1 | tee -a /scratch/art-daq/build.log
            res=\${PIPESTATUS[0]} # Get result of first command in previous pipe, bash specific
        fi

        exit \$res
        EOT
        chmod +x build_pkg.sh

        docker run --rm -v /cvmfs:/cvmfs:shared -v $GITHUB_WORKSPACE/scratch:/scratch ghcr.io/art-daq/otsdaq-spack:latest /scratch/build_pkg.sh
        
    - name: Check build log for success
      run: |
        grep "100% tests passed, 0 tests failed" ${{ github.workspace }}/scratch/art-daq/build.log ||
        grep "No tests were found!!!" ${{ github.workspace }}/scratch/art-daq/build.log

    - name: upload build log file
      uses: actions/upload-artifact@main
      with:
        name: build_log
        path: ${{ github.workspace }}/scratch/art-daq/build.log

    - name: change dir permission again
      run: |
        sudo chmod -R go+rwx /var/lib/cvmfs
